/*
    This file was generated by the aggregate-types script.
    
       This file is a combination of all TypeScript types in the client-types directory.
    
       This is to make sure that the client application has access to all the types in the client-types directory and we have consistent types across the app.
    
       To regenerate this file, run the aggregate-types script.
    
       From the API directory, run:  `node aggregate-types.js`
    
       Authored by: @AnguleMathias :)
    */
/**
 * Interface representing a user
 * @interface
 */
export interface IUser {
  /**
   * The unique identifier for the user
   * @example '123e4567-e89b-12d3-a456-426614174000'
   * @type {string}
   */
  id: string;

  /**
   * The username of the user
   * @example 'john_doe'
   * @type {string}
   */
  username: string;

  /**
   * The email address of the user
   * @example 'john_doe@example.com'
   * @type {string}
   */
  email: string;

  /**
   * The hashed password of the user
   * @example '$2b$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36T8EnzO3W7hdA2kB18Y.yC'
   * @type {string}
   */
  password: string;

  /**
   * The date and time when the user was created
   * @example '2024-05-01T00:00:00Z'
   * @type {Date}
   */
  createdAt: Date;

  /**
   * The date and time when the user was last updated
   * @example '2024-05-20T00:00:00Z'
   * @type {Date}
   */
  updatedAt: Date;
}

/**
 * Interface for creating a new user
 * @interface
 */
export interface ICreateUserDto {
  /**
   * The username of the user
   * @type {string}
   */
  username: string;

  /**
   * The email address of the user
   * @type {string}
   */
  email: string;

  /**
   * The password of the user
   * @type {string}
   */
  password: string;
}

/**
 * Interface for updating an existing user
 * @interface
 */
export interface IUpdateUserDto {
  /**
   * The username of the user
   * @type {string}
   */
  username?: string;

  /**
   * The email address of the user
   * @type {string}
   */
  email?: string;

  /**
   * The password of the user
   * @type {string}
   */
  password?: string;
}

/**
 * Interface representing a task
 * @interface
 */
export interface ITask {
  /**
   * The unique identifier for the task
   * @example '123e4567-e89b-12d3-a456-426614174000'
   * @type {string}
   */
  id: string;

  /**
   * The title of the task
   * @example 'Finish the report'
   * @type {string}
   */
  title: string;

  /**
   * A detailed description of the task
   * @example 'Complete the quarterly report by end of the week'
   * @type {string}
   */
  description: string;

  /**
   * The due date of the task
   * @example '2024-05-26T00:00:00Z'
   * @type {Date}
   */
  due_date: Date;

  /**
   * The priority of the task
   * @example 'High'
   * @enum ['Low', 'Medium', 'High']
   * @type {string}
   */
  priority: 'Low' | 'Medium' | 'High';

  /**
   * The status of the task
   * @example 'Pending'
   * @enum ['Pending', 'In Progress', 'Completed']
   * @type {string}
   */
  status: 'Pending' | 'In Progress' | 'Completed';

  /**
   * The identifier of the user assigned to the task
   * @example '123e4567-e89b-12d3-a456-426614174001'
   * @type {string}
   */
  assignee: string;

  /**
   * The date and time when the task was created
   * @example '2024-05-01T00:00:00Z'
   * @type {Date}
   */
  createdAt: Date;

  /**
   * The date and time when the task was last updated
   * @example '2024-05-20T00:00:00Z'
   * @type {Date}
   */
  updatedAt: Date;
}

/**
 * Interface for creating a new task
 * @interface
 */
export interface ICreateTaskDto {
  /**
   * The title of the task
   * @type {string}
   */
  title: string;

  /**
   * A detailed description of the task
   * @type {string}
   */
  description: string;

  /**
   * The due date of the task
   * @type {Date}
   */
  due_date: Date;

  /**
   * The priority of the task
   * @enum ['Low', 'Medium', 'High']
   * @type {string}
   */
  priority: 'Low' | 'Medium' | 'High';

  /**
   * The status of the task
   * @enum ['Pending', 'In Progress', 'Completed']
   * @type {string}
   */
  status: 'Pending' | 'In Progress' | 'Completed';

  /**
   * The identifier of the user assigned to the task
   * @type {string}
   */
  assignee: string;
}

/**
 * Interface for updating an existing task
 * @interface
 */
export interface IUpdateTaskDto {
  /**
   * The title of the task
   * @type {string}
   */
  title?: string;

  /**
   * A detailed description of the task
   * @type {string}
   */
  description?: string;

  /**
   * The due date of the task
   * @type {Date}
   */
  due_date?: Date;

  /**
   * The priority of the task
   * @enum ['Low', 'Medium', 'High']
   * @type {string}
   */
  priority?: 'Low' | 'Medium' | 'High';

  /**
   * The status of the task
   * @enum ['Pending', 'In Progress', 'Completed']
   * @type {string}
   */
  status?: 'Pending' | 'In Progress' | 'Completed';

  /**
   * The identifier of the user assigned to the task
   * @type {string}
   */
  assignee?: string;
}
